# Generated by Django 5.0.2 on 2024-02-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('Read Only', 'Read Only'), ('Read/Write', 'Read/Write')], max_length=50, verbose_name='Access Level')),
                ('joined_at', models.DateTimeField(verbose_name='Joined At')),
                ('left_at', models.DateTimeField(verbose_name='Left At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('document_content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Edits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('changes_made', models.JSONField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.documents', verbose_name='Documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
